import {
  ApiHideProperty,
  ApiProperty,
  ApiPropertyOptional,
  OmitType,
  PartialType,
} from '@nestjs/swagger';
import { Transform, Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsDateString,
  IsEmpty,
  IsIn,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Max,
  Min,
  ValidateNested,
} from 'class-validator';
import {
  discountCodeTypes,
  DiscountCodeType,
} from '../entities/discount-code.entity';
import { discountTypes, DiscountType } from '../entities/discount.entity';
import { OptionalNotNull } from '~/common/decorator/optional-not-null.decorator';

export const discountTargetTypes = ['kelas', 'digital'] as const;

export type DiscountTargetType = (typeof discountTargetTypes)[number];

export class DiscountTargetInputDto {
  @ApiProperty({
    enum: discountTargetTypes,
    description: 'kelas = class, digital = digital product',
  })
  @IsIn(discountTargetTypes)
  type: DiscountTargetType;

  @ApiProperty({ description: 'Class id or digital product id' })
  @IsUUID()
  id: string;
}

export class DiscountCodeInputDto {
  @ApiProperty({
    enum: discountCodeTypes,
    description:
      'once = single-use codes ("Kode Sekali Pakai"); recurring = one shared code ("Kode Berulang")',
  })
  @IsIn(discountCodeTypes)
  code_type: DiscountCodeType;

  @ApiProperty({
    example: 100,
    minimum: 1,
    maximum: 100000,
    description:
      'once: how many single-use codes to generate (at most 1,000 per request in total); recurring: total uses of the shared code',
  })
  @IsInt()
  @Min(1)
  @Max(100000)
  usage_limit: number;

  // Codes are generated by the system; a client-supplied string is rejected.
  @ApiHideProperty()
  @IsEmpty({ message: 'code is generated by the system and must not be sent' })
  code?: never;
}

export class CreateDiscountDto {
  @ApiProperty({ example: 'Diskon Kilat AutoCAD', maxLength: 120 })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @Length(1, 120)
  name: string;

  @ApiProperty({ enum: discountTypes })
  @IsIn(discountTypes)
  discount_type: DiscountType;

  @ApiProperty({ example: 20, description: 'Percent (1-100) or rupiah amount' })
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0.01)
  discount_value: number;

  @ApiPropertyOptional({ example: 100000, nullable: true })
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  minimum_purchase?: number | null;

  @ApiPropertyOptional({ nullable: true })
  @IsOptional()
  @IsDateString()
  starts_at?: string | null;

  @ApiPropertyOptional({ nullable: true })
  @IsOptional()
  @IsDateString()
  ends_at?: string | null;

  @ApiPropertyOptional({ default: true })
  @OptionalNotNull()
  @IsBoolean()
  is_active?: boolean;

  @ApiPropertyOptional({
    type: [DiscountTargetInputDto],
    description: 'Empty or omitted = all of the merchant products',
  })
  @OptionalNotNull()
  @IsArray()
  @ArrayMaxSize(200)
  @ValidateNested({ each: true })
  @Type(() => DiscountTargetInputDto)
  targets?: DiscountTargetInputDto[];

  @ApiPropertyOptional({ type: [DiscountCodeInputDto], maxItems: 50 })
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(50)
  @ValidateNested({ each: true })
  @Type(() => DiscountCodeInputDto)
  codes?: DiscountCodeInputDto[];
}

// Null is validated, so it is rejected for fields that cannot be cleared.
export class UpdateDiscountDto extends PartialType(
  OmitType(CreateDiscountDto, ['codes'] as const),
  { skipNullProperties: false },
) {}

export class AddDiscountCodesDto {
  @ApiProperty({ type: [DiscountCodeInputDto], minItems: 1, maxItems: 50 })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(50)
  @ValidateNested({ each: true })
  @Type(() => DiscountCodeInputDto)
  codes: DiscountCodeInputDto[];
}

export class DiscountListQueryDto {
  @ApiPropertyOptional({ default: 1, minimum: 1 })
  @IsOptional()
  @Transform(({ value }) => Number(value))
  @IsInt()
  @Min(1)
  page = 1;

  @ApiPropertyOptional({ default: 20, minimum: 1, maximum: 100 })
  @IsOptional()
  @Transform(({ value }) => Number(value))
  @IsInt()
  @Min(1)
  @Max(100)
  limit = 20;
}
