import {
  ApiHideProperty,
  ApiProperty,
  ApiPropertyOptional,
  OmitType,
  PartialType,
} from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  ArrayUnique,
  IsArray,
  IsBoolean,
  IsDateString,
  IsEmpty,
  IsNumber,
  IsOptional,
  IsUUID,
  ValidateNested,
} from 'class-validator';
import {
  discountCodeTypes,
  DiscountCodeType,
} from '../entities/discount-code.entity';
import { discountTypes, DiscountType } from '../entities/discount.entity';
import { OptionalNotNull } from '~/common/decorator/optional-not-null.decorator';
import {
  EnumInput,
  NumberInput,
  RequiredText,
} from '~/common/decorator/input.decorator';
import { LimitQuery, PageQuery } from '~/common/dto/request-paginated.dto';
import {
  ContentItemType,
  contentItemTypes,
} from '~/common/catalog/catalog-item';

// Matches the most single-use codes one request can generate.
const MAX_REMOVED_CODES_PER_REQUEST = 1000;

export const discountTargetTypes = ['kelas', 'digital'] as const;

export type DiscountTargetType = (typeof discountTargetTypes)[number];

export class DiscountTargetInputDto {
  @EnumInput(contentItemTypes, {
    presence: 'filter',
    description:
      'Optional: resolved from the id. When sent it must name the item family (kelas or bootcamp for a class, digital for a digital product).',
  })
  type?: ContentItemType;

  @ApiProperty({ description: 'Class id or digital product id' })
  @IsUUID()
  id: string;
}

export class DiscountCodeInputDto {
  @EnumInput(discountCodeTypes, {
    description:
      'once = single-use codes ("Kode Sekali Pakai"); recurring = one shared code ("Kode Berulang")',
  })
  code_type: DiscountCodeType;

  @NumberInput({
    integer: true,
    min: 1,
    max: 100000,
    example: 100,
    description:
      'once: how many single-use codes to generate (at most 1,000 per request in total); recurring: total uses of the shared code',
  })
  usage_limit: number;

  // Codes are generated by the system; a client-supplied string is rejected.
  @ApiHideProperty()
  @IsEmpty({ message: 'code is generated by the system and must not be sent' })
  code?: never;
}

export class CreateDiscountDto {
  @RequiredText({ max: 120, example: 'Diskon Kilat AutoCAD' })
  name: string;

  @EnumInput(discountTypes)
  discount_type: DiscountType;

  @NumberInput({
    min: 0.01,
    example: 20,
    description: 'Percent (1-100) or rupiah amount',
  })
  @IsNumber({ maxDecimalPlaces: 2 })
  discount_value: number;

  @NumberInput({ presence: 'nullable', min: 0, example: 100000 })
  @IsNumber({ maxDecimalPlaces: 2 })
  minimum_purchase?: number | null;

  @ApiPropertyOptional({ nullable: true })
  @IsOptional()
  @IsDateString()
  starts_at?: string | null;

  @ApiPropertyOptional({ nullable: true })
  @IsOptional()
  @IsDateString()
  ends_at?: string | null;

  @ApiPropertyOptional({ default: true })
  @OptionalNotNull()
  @IsBoolean()
  is_active?: boolean;

  @ApiPropertyOptional({
    type: [DiscountTargetInputDto],
    description: 'Empty or omitted = all of the merchant products',
  })
  @OptionalNotNull()
  @IsArray()
  @ArrayMaxSize(200)
  @ValidateNested({ each: true })
  @Type(() => DiscountTargetInputDto)
  targets?: DiscountTargetInputDto[];

  @ApiPropertyOptional({ type: [DiscountCodeInputDto], maxItems: 50 })
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(50)
  @ValidateNested({ each: true })
  @Type(() => DiscountCodeInputDto)
  codes?: DiscountCodeInputDto[];
}

// Null is validated, so it is rejected for fields that cannot be cleared.
export class UpdateDiscountDto extends PartialType(
  OmitType(CreateDiscountDto, ['codes'] as const),
  { skipNullProperties: false },
) {}

export class AddDiscountCodesDto {
  @ApiProperty({ type: [DiscountCodeInputDto], minItems: 1, maxItems: 50 })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(50)
  @ValidateNested({ each: true })
  @Type(() => DiscountCodeInputDto)
  codes: DiscountCodeInputDto[];
}

export class RemoveDiscountCodesDto {
  @ApiProperty({
    type: [String],
    format: 'uuid',
    minItems: 1,
    maxItems: MAX_REMOVED_CODES_PER_REQUEST,
    uniqueItems: true,
    description: 'Ids of codes of this discount',
  })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(MAX_REMOVED_CODES_PER_REQUEST)
  @ArrayUnique()
  @IsUUID('all', { each: true })
  code_ids: string[];
}

export class DiscountListQueryDto {
  @PageQuery()
  page = 1;

  @LimitQuery()
  limit = 10;
}
